attendee/pom.xml
attendee/src/main/kotlin/de/kordondev/attendee/AttendeeApplication.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/model/Attendee.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/model/User.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/AttendeeEntry.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/UserEntry.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/repository/UserRepository.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/security/AuthorityService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/security/JWTAuthenticationFilter.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/security/JWTAuthorizationFilter.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/security/SecurityConstants.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/security/SpringSecurityConfig.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/security/UserDetailsServiceImpl.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/AttendeeService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/DepartmentService.kt
attendee/src/main/kotlin/de/kordondev/attendee/exception/ExceptionHandler.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/RestUser.kt
attendee/src/test/kotlin/de/kordondev/attendee/core/security/HasAuthorityTest.kt

4 authentication

---

attendee/demo-requests/createAttendee.sh
attendee/demo-requests/getAttendee.sh
attendee/demo-requests/getDepartment.sh
attendee/demo-requests/login.sh
attendee/docker-compose/docker-compose.yml
attendee/pom.xml
attendee/src/main/resources/application.properties

17 database

---

attendee/src/main/kotlin/de/kordondev/attendee/AttendeeApplication.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/model/Attendee.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/AttendeeEntry.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/AttendeeRole.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/Food.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/TShirtSize.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/UserEntry.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/AttendeeController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/RestAttendee.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/request/RestAttendeeRequest.kt
attendee/src/test/kotlin/de/kordondev/attendee/core/security/HasAuthorityTest.kt

More properties for Attendees

---

attendee/pom.xml
attendee/src/main/kotlin/de/kordondev/attendee/rest/swagger/SwaggerConfiguration.kt

Added swagger

---

attendee/pom.xml
attendee/src/main/kotlin/de/kordondev/attendee/AttendeeApplication.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/mail/MailSenderService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/model/User.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/repository/AttendeeRepository.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/security/PasswordGenerator.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/AttendeeService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/DepartmentService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/MailService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/UserService.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/AttendeeController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/DepartmentController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/UserController.kt

Easy fixes

---

attendee/src/main/kotlin/de/kordondev/attendee/AttendeeApplication.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/mail/MailSenderService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/security/AuthorityService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/AttendeeService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/DepartmentService.kt
attendee/src/test/kotlin/de/kordondev/attendee/core/security/HasAuthorityTest.kt

23 new role specialized field director

---

attendee/demo-requests/createAttendee.sh
attendee/pom.xml
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/AttendeeController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/DepartmentController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/MailController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/UserController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/request/RestAttendeeRequest.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/request/RestDepartmentRequest.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/request/RestSendMailRequest.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/request/RestUserRequest.kt

Add validation

---

attendee/src/main/kotlin/de/kordondev/attendee/core/security/SpringSecurityConfig.kt
frontend/src/components/AttendeesRegistration.vue
frontend/src/components/AttendeesTable.vue
frontend/src/components/Header.vue
frontend/src/helper/fetch.ts
frontend/src/router/index.ts
frontend/src/services/attendee.ts
frontend/src/services/authentication.ts
frontend/src/services/department.ts
frontend/src/views/AttendeesRegistrationView.vue

12 11 edit add attendees

---

attendee/demo-requests/createMockData.js
attendee/src/main/kotlin/de/kordondev/attendee/core/security/SpringSecurityConfig.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/AttendeeController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/RestAttendee.kt
frontend/src/components/AttendeesRegistration.vue
frontend/src/components/AttendeesTable.vue
frontend/src/services/attendee.ts

WIP: 42 add delete and edit attendees

---

frontend/package.json
frontend/src/components/AttendeesRegistration.vue
frontend/src/components/AttendeesTable.vue
frontend/src/components/BarChart.vue
frontend/src/components/Distribution.vue
frontend/src/components/Header.vue
frontend/src/components/Overview.vue
frontend/src/helper/displayText.ts
frontend/src/helper/filterHelper.ts
frontend/src/router/index.ts
frontend/src/services/attendee.ts
frontend/src/services/authentication.ts
frontend/yarn.lock

14 admin overview

---

attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/RegistrationFilesController.kt
frontend/src/components/FileList.vue
frontend/src/components/Header.vue
frontend/src/components/Overview.vue
frontend/src/components/RegistrationFiles.vue
frontend/src/helper/fetch.ts
frontend/src/router/index.ts
frontend/src/services/registrationFiles.ts

Show all files in frontend

---

attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/repository/AttendeeRepository.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/AttendeeService.kt
attendee/src/main/kotlin/de/kordondev/attendee/exception/ExceptionHandler.kt
attendee/src/main/kotlin/de/kordondev/attendee/exception/UniqueException.kt

Firstname and lastname should be unique

---

attendee/src/main/kotlin/de/kordondev/attendee/core/service/AttendeeService.kt

Check id for found attendees

---

frontend/src/components/settings/EventsConfiguration.vue

Add link to event page

---

frontend/src/components/Scanner.vue

Stop Quagga when scanner is destroyed

---

attendee/src/main/resources/mail/new-user.html
attendee/src/main/resources/mail/registration-finished.html
attendee/src/main/resources/mail/reminder.html

Resize picture

---

frontend/src/components/Header.vue
frontend/src/components/Login.vue
frontend/src/components/Scanner.vue
frontend/src/components/settings/EditSettings.vue
frontend/src/components/settings/MailSettings.vue

fix all console errors

---

attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/SettingsEntry.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/AttendeeService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/SettingsService.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/SettingsController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/request/RestRegistrationEnd.kt
attendee/src/main/resources/db/scripts/002_add-settings.xml
frontend/src/components/AttendeesRegistration.vue
frontend/src/components/AttendeesTable.vue
frontend/src/components/RegistrationFiles.vue
frontend/src/components/settings/EventsConfiguration.vue
frontend/src/services/settings.ts

set up registration end as date with diff and hide use interactions if date reached

---

frontend/src/helper/fetch.ts

Show special message for login

---

frontend/src/App.vue
frontend/src/components/AttendeeList.vue
frontend/src/components/AttendeesRegistration.vue
frontend/src/components/DateAndTime.vue
frontend/src/components/EditDepartment.vue
frontend/src/components/Footer.vue
frontend/src/components/Header.vue
frontend/src/components/ListDepartment.vue
frontend/src/components/Login.vue
frontend/src/components/Overview.vue
frontend/src/components/RegistrationFiles.vue
frontend/src/components/Scanner.vue
frontend/src/components/settings/EditSettings.vue
frontend/src/components/settings/EventsConfiguration.vue
frontend/src/components/settings/MailSettings.vue
frontend/src/components/settings/PcrTestsConfiguration.vue
frontend/src/router/index.ts
frontend/src/views/AccountView.vue
frontend/src/views/SettingsView.vue

update open frontend tasks and refactor, add footer style

---

frontend/src/components/Login.vue

Show notification after failing login

---

attendee/docker-compose/docker-compose.yml

Please check if this works for you

Fix backend to database connection

---

attendee/src/main/kotlin/de/kordondev/attendee/core/pdf/PDFHelper.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/AdminFilesService.kt
frontend/src/components/Overview.vue

Show bracelet per department

---

frontend/src/components/AddDepartment.vue
frontend/src/components/settings/EditSettings.vue
frontend/src/components/settings/EventsConfiguration.vue
frontend/src/components/settings/MailSettings.vue
frontend/src/components/settings/PcrTestsConfiguration.vue

Add more notifications

---

attendee/src/main/kotlin/de/kordondev/attendee/core/model/Settings.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/entry/SettingsEntry.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/RegistrationFilesService.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/SettingsService.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/SettingsController.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/RestSettings.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/request/RestSettingsRequest.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/model/request/RestStartDownloadRegistrationFiles.kt
attendee/src/main/resources/db/changelog-master.xml
attendee/src/main/resources/db/scripts/010_add-start-of-registration-files-date.xml
frontend/src/components/RegistrationFiles.vue
frontend/src/components/settings/EditSettings.vue
frontend/src/services/settings.ts

Add start download of registration files

---

attendee/src/main/kotlin/de/kordondev/attendee/core/persistence/repository/EventRepository.kt
attendee/src/main/kotlin/de/kordondev/attendee/core/service/EventService.kt
attendee/src/main/kotlin/de/kordondev/attendee/rest/controller/EventController.kt
frontend/src/components/Overview.vue
frontend/src/services/event.ts

Register whole department

---

attendee/src/main/kotlin/de/kordondev/attendee/core/pdf/AttendeesCommunal.kt

Write event address for communal pdf

---

attendee/src/main/kotlin/de/kordondev/attendee/core/pdf/StateYouthPlanAttendees.kt

Fix sum of days

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/persistence/repository/AttendeeRepository.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/AttendeeService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/DepartmentService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/DepartmentController.kt
frontend/src/components/LmRegistrationFiles.vue
frontend/src/services/department.ts

Hide departments without attendees in registration files view

---

backend/src/main/kotlin/de/kordondev/lagermelder/Helper.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/AttendeeService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/PlanningFilesService.kt

Add helper and zkids to all planning files

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/service/PlanningFilesService.kt

No batch for helper

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/service/PlanningFilesService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/PlanningFilesController.kt
frontend/src/components/LmPlanning.vue
frontend/src/components/departmentsOverview/LmListDepartment.vue
frontend/src/services/planningFiles.ts

Download contact list

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/service/PlanningFilesService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/PlanningFilesController.kt
frontend/src/components/LmPlanning.vue
frontend/src/services/planningFiles.ts

Add download for batches ordered by creation date

---

.vscode/launch.json
frontend/src/components/AttendeeExpansionPanel/LmAttendeeExpandableWithHeader.vue
frontend/src/components/LmAttendeesRegistration.vue

feat: scroll to last added and animate for better usability

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/service/PlanningFilesService.kt
frontend/src/components/AttendeeExpansionPanel/LmAttendeeAddForm.vue
frontend/src/components/AttendeeExpansionPanel/LmAttendeeExpansionPanel.vue

Hide tShirt

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/persistence/entry/SettingsEntry.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/SettingsService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/UserService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/SettingsController.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/model/RestSettings.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/model/request/RestRegistrationEnd.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/model/request/RestSettingsRequest.kt
backend/src/main/resources/db/changelog-main.xml
backend/src/main/resources/db/scripts/026_add_helper_registration_end.xml
frontend/src/components/LmAttendeesRegistration.vue
frontend/src/components/settings/LmEditSettings.vue
frontend/src/services/settings.ts
frontend/src/views/AccountView.vue

Add registration date for helper

---

backend/docker-compose/docker-compose.yml
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/SettingsService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/SettingsController.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/model/request/RestRegistrationEnd.kt
frontend/.npmrc
frontend/src/components/AttendeeExpansionPanel/LmAttendeeExpandableWithHeader.vue
frontend/src/components/AttendeeExpansionPanel/LmAttendeeExpansionPanel.vue
frontend/src/components/LmAttendeesRegistration.vue
frontend/src/components/LmRegistrationInformation.vue
frontend/src/helper/juleika.ts
frontend/src/services/settings.ts

Can stop editing attendees

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/service/DepartmentService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/DepartmentController.kt

User can save contact details

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/service/DepartmentService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/EventService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/PlanningFilesService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/SettingsService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/YouthPlanAttendeeRoleService.kt
frontend/src/components/LmEvacuationConfiguration.vue
frontend/src/components/LmYouthPlanDistribution.vue
frontend/src/services/department.ts
frontend/src/views/EventsView.vue

Various small fixes

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/service/EventService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/model/RestGlobalEventSummary.kt
frontend/src/components/LmCheckedInSummary.vue
frontend/src/services/event.ts
frontend/src/views/EventSummaryView.vue

fix: remove ppaused form distribution and use paused from department

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/service/DepartmentService.kt
frontend/src/views/EventSummaryView.vue

Filter ansenend to departments with attendees and update total number

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/pdf/StateYouthPlanLeader.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/YouthPlanAttendeeRoleService.kt

add sonderurlaub and move juleika data

---

backend/src/main/kotlin/de/kordondev/lagermelder/core/persistence/repository/BaseAttendeeRepository.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/security/SpringSecurityConfig.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/AttendeeService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/DepartmentService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/EventService.kt
backend/src/main/kotlin/de/kordondev/lagermelder/core/service/models/RoleCount.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/DepartmentController.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/EventController.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/controller/PublicController.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/model/RestGlobalEventSummary.kt
backend/src/main/kotlin/de/kordondev/lagermelder/rest/model/RestRoleCount.kt
frontend/src/components/LmCheckedInSummary.vue
frontend/src/services/attendee.ts
frontend/src/services/event.ts
frontend/src/views/DepartmentBatchEnter.vue
frontend/src/views/EventSummaryView.vue

Add api to count present people
